remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
title: Steve Krug
description: This site is made to be a portfolio of sorts for my dive into offensive security. I'll post write ups, information, etc.. here. 
